[dots] upgrade uv tools

diff --git a/.local/dotsbin/dots-postupdate b/.local/dotsbin/dots-postupdate
--- a/.local/dotsbin/dots-postupdate
+++ b/.local/dotsbin/dots-postupdate
@@ -24,6 +24,11 @@ if command -v pipx > /dev/null 2>&1; then
     pipx upgrade-all || die "pipx update failed"
 fi
 
+if command -v uv > /dev/null 2>&1; then
+    einfo "updating uv tools"
+    uv tool upgrade --all || die "pipx update failed"
+fi
+
 if [ -d ~/.mozilla/firefox ]; then
     for i in ~/.mozilla/firefox/*/; do
         einfo "installing Betterfox in $i"
