[git] improve default hooks
print commands being run
and run the commands correctly

diff --git a/.config/git/hooks/pre-commit b/.config/git/hooks/pre-commit
--- a/.config/git/hooks/pre-commit
+++ b/.config/git/hooks/pre-commit
@@ -1,12 +1,24 @@
-#!/bin/sh
-set -e
+#!/bin/bash
+
+die() {
+	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
+	exit 1
+}
+
+einfo() {
+	echo -e " ${NOCOLOR-\e[1;32m*\e[0m }${*}" >&2
+}
+
+ewarn() {
+	echo -e " ${NOCOLOR-\e[1;33m*\e[0m }${*}" >&2
+}
+
 
 runif() {
     if [ -n "$1" ]; then
         shift
-        # shellcheck disable=SC2068
-        sh -c "$@"
-        return $?
+        einfo "$*"
+        sh -c "$*" || die "$*: failed"
     fi
     return 0
 }
